secIDNum = 2
indIDNum = 6
secID = [0] * secIDNum
indID = [0] * indIDNum
gdata = [[0 for col in range(indIDNum)] for row in range(secIDNum)]
spreadBid = 0
spreadAsk = 0
spreadLast = 0
plotLast = []
plotBid = []
plotAsk = []
plotTime = []
