# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quote.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

# The script have been updated for PyQt5

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8


    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1142, 629)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bidvol1Edit = QtWidgets.QLineEdit(Dialog)
        self.bidvol1Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bidvol1Edit.setFont(font)
        self.bidvol1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.bidvol1Edit.setFrame(False)
        self.bidvol1Edit.setObjectName(_fromUtf8("bidvol1Edit"))
        self.gridLayout.addWidget(self.bidvol1Edit, 1, 3, 1, 1)
        self.label1 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 1, 0, 1, 1)
        self.sec2Edit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.sec2Edit.setFont(font)
        self.sec2Edit.setStyleSheet(_fromUtf8("background-color: rgb(255, 109, 24);\n"
                                              "color: rgb(255, 255, 255);"))
        self.sec2Edit.setFrame(False)
        self.sec2Edit.setObjectName(_fromUtf8("sec2Edit"))
        self.gridLayout.addWidget(self.sec2Edit, 2, 1, 1, 1)
        self.label7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label7.setFont(font)
        self.label7.setObjectName(_fromUtf8("label7"))
        self.gridLayout.addWidget(self.label7, 0, 6, 1, 1)
        self.bid2Edit = QtWidgets.QLineEdit(Dialog)
        self.bid2Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bid2Edit.setFont(font)
        self.bid2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                              "background-color: rgb(0, 0, 127);"))
        self.bid2Edit.setFrame(False)
        self.bid2Edit.setObjectName(_fromUtf8("bid2Edit"))
        self.gridLayout.addWidget(self.bid2Edit, 2, 4, 1, 1)
        self.label6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label6.setFont(font)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.gridLayout.addWidget(self.label6, 0, 5, 1, 1)
        self.spread2Edit = QtWidgets.QLineEdit(Dialog)
        self.spread2Edit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spread2Edit.setFont(font)
        self.spread2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.spread2Edit.setFrame(False)
        self.spread2Edit.setObjectName(_fromUtf8("spread2Edit"))
        self.gridLayout.addWidget(self.spread2Edit, 3, 5, 1, 1)
        self.ask1Edit = QtWidgets.QLineEdit(Dialog)
        self.ask1Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ask1Edit.setFont(font)
        self.ask1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                              "background-color: rgb(0, 0, 127);"))
        self.ask1Edit.setFrame(False)
        self.ask1Edit.setObjectName(_fromUtf8("ask1Edit"))
        self.gridLayout.addWidget(self.ask1Edit, 1, 5, 1, 1)
        self.askvol1Edit = QtWidgets.QLineEdit(Dialog)
        self.askvol1Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.askvol1Edit.setFont(font)
        self.askvol1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.askvol1Edit.setText(_fromUtf8(""))
        self.askvol1Edit.setFrame(False)
        self.askvol1Edit.setObjectName(_fromUtf8("askvol1Edit"))
        self.gridLayout.addWidget(self.askvol1Edit, 1, 6, 1, 1)
        self.last2Edit = QtWidgets.QLineEdit(Dialog)
        self.last2Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.last2Edit.setFont(font)
        self.last2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                               "background-color: rgb(0, 0, 127);"))
        self.last2Edit.setFrame(False)
        self.last2Edit.setObjectName(_fromUtf8("last2Edit"))
        self.gridLayout.addWidget(self.last2Edit, 2, 2, 1, 1)
        self.spread1Edit = QtWidgets.QLineEdit(Dialog)
        self.spread1Edit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spread1Edit.setFont(font)
        self.spread1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.spread1Edit.setFrame(False)
        self.spread1Edit.setObjectName(_fromUtf8("spread1Edit"))
        self.gridLayout.addWidget(self.spread1Edit, 3, 4, 1, 1)
        self.label5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label5.setFont(font)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.gridLayout.addWidget(self.label5, 0, 4, 1, 1)
        self.askvol2Edit = QtWidgets.QLineEdit(Dialog)
        self.askvol2Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.askvol2Edit.setFont(font)
        self.askvol2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.askvol2Edit.setFrame(False)
        self.askvol2Edit.setObjectName(_fromUtf8("askvol2Edit"))
        self.gridLayout.addWidget(self.askvol2Edit, 2, 6, 1, 1)
        self.bid1Edit = QtWidgets.QLineEdit(Dialog)
        self.bid1Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bid1Edit.setFont(font)
        self.bid1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                              "background-color: rgb(0, 0, 127);"))
        self.bid1Edit.setFrame(False)
        self.bid1Edit.setObjectName(_fromUtf8("bid1Edit"))
        self.gridLayout.addWidget(self.bid1Edit, 1, 4, 1, 1)
        self.last1Edit = QtWidgets.QLineEdit(Dialog)
        self.last1Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.last1Edit.setFont(font)
        self.last1Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                               "background-color: rgb(0, 0, 127);"))
        self.last1Edit.setFrame(False)
        self.last1Edit.setReadOnly(True)
        self.last1Edit.setObjectName(_fromUtf8("last1Edit"))
        self.gridLayout.addWidget(self.last1Edit, 1, 2, 1, 1)
        self.label2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 2, 0, 1, 1)
        self.sec1Edit = QtWidgets.QLineEdit(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        self.sec1Edit.setFont(font)
        self.sec1Edit.setStyleSheet(_fromUtf8("background-color: rgb(255, 109, 24);\n"
                                              "color: rgb(255, 255, 255);"))
        self.sec1Edit.setFrame(False)
        self.sec1Edit.setObjectName(_fromUtf8("sec1Edit"))
        self.gridLayout.addWidget(self.sec1Edit, 1, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.gridLayout.addWidget(self.label4, 0, 3, 1, 1)
        self.label8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label8.setFont(font)
        self.label8.setObjectName(_fromUtf8("label8"))
        self.gridLayout.addWidget(self.label8, 3, 0, 1, 2)
        self.label3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 0, 2, 1, 1)
        self.ask2Edit = QtWidgets.QLineEdit(Dialog)
        self.ask2Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.ask2Edit.setFont(font)
        self.ask2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                              "background-color: rgb(0, 0, 127);"))
        self.ask2Edit.setFrame(False)
        self.ask2Edit.setObjectName(_fromUtf8("ask2Edit"))
        self.gridLayout.addWidget(self.ask2Edit, 2, 5, 1, 1)
        self.bidvol2Edit = QtWidgets.QLineEdit(Dialog)
        self.bidvol2Edit.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.bidvol2Edit.setFont(font)
        self.bidvol2Edit.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
                                                 "background-color: rgb(0, 0, 127);"))
        self.bidvol2Edit.setFrame(False)
        self.bidvol2Edit.setObjectName(_fromUtf8("bidvol2Edit"))
        self.gridLayout.addWidget(self.bidvol2Edit, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.subscribeButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.subscribeButton.setFont(font)
        self.subscribeButton.setObjectName(_fromUtf8("subscribeButton"))
        self.verticalLayout.addWidget(self.subscribeButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.verticalLayout.addWidget(self.cancelButton)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 268, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.horizontalLayout.addWidget(self.graphicsView)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label9 = QtWidgets.QLabel(Dialog)
        self.label9.setObjectName(_fromUtf8("label9"))
        self.verticalLayout_2.addWidget(self.label9)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 127);\n"
                                                 "color: rgb(255, 255, 255);"))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.label1.setBuddy(self.sec1Edit)
        self.label2.setBuddy(self.sec2Edit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.sec1Edit, self.sec2Edit)
        Dialog.setTabOrder(self.sec2Edit, self.subscribeButton)
        Dialog.setTabOrder(self.subscribeButton, self.cancelButton)
        Dialog.setTabOrder(self.cancelButton, self.graphicsView)
        Dialog.setTabOrder(self.graphicsView, self.textBrowser)
        Dialog.setTabOrder(self.textBrowser, self.last1Edit)
        Dialog.setTabOrder(self.last1Edit, self.last2Edit)
        Dialog.setTabOrder(self.last2Edit, self.bidvol1Edit)
        Dialog.setTabOrder(self.bidvol1Edit, self.bidvol2Edit)
        Dialog.setTabOrder(self.bidvol2Edit, self.bid1Edit)
        Dialog.setTabOrder(self.bid1Edit, self.bid2Edit)
        Dialog.setTabOrder(self.bid2Edit, self.ask1Edit)
        Dialog.setTabOrder(self.ask1Edit, self.ask2Edit)
        Dialog.setTabOrder(self.ask2Edit, self.askvol1Edit)
        Dialog.setTabOrder(self.askvol1Edit, self.askvol2Edit)
        Dialog.setTabOrder(self.askvol2Edit, self.spread1Edit)
        Dialog.setTabOrder(self.spread1Edit, self.spread2Edit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label1.setText(_translate("Dialog", "SecurityID", None))
        self.sec2Edit.setText(_translate("Dialog", "eurusd.fx", None))
        self.label7.setText(_translate("Dialog", "AskVol", None))
        self.label6.setText(_translate("Dialog", "AskPrice", None))
        self.label5.setText(_translate("Dialog", "BidPrice", None))
        self.label2.setText(_translate("Dialog", "SecurityID", None))
        self.sec1Edit.setText(_translate("Dialog", "gbpusd.fx", None))
        self.label4.setText(_translate("Dialog", "BidVol", None))
        self.label8.setText(_translate("Dialog", "Spread", None))
        self.label3.setText(_translate("Dialog", "Last", None))
        self.subscribeButton.setText(_translate("Dialog", "Subscribe", None))
        self.cancelButton.setText(_translate("Dialog", "unSubscribe", None))
        self.label9.setText(_translate("Dialog", "spread records", None))
